### ISSUE TITLE
EOL while scanning string literal

### ISSUE THREAD

**Issue by carangelmx** [fork52/chess_gif#1]
Hello, 

I performed the instllation instructions, and then I run the following code:
from chess_gif.gif_maker import Gifmaker
obj = Gifmaker('sample.pgn')
obj.make_gif('chess_game.gif)

The last line produces the following error:
*******
obj.make_gif('chess_game.gif)
  File "<ipython-input-7-06202280f117>", line 1
    obj.make_gif('chess_game.gif)
                                 ^
SyntaxError: EOL while scanning string literal
*******
What I did wrong?

**Comment by carangelmx** [comment]
Sorry, I answered myself!

**Comment by fork52** [comment]
My bad I did I a typo mistake in the readme. Thanks for bringing this up!
