### ISSUE TITLE
Set delay in seconds betweeen individual moves

### ISSUE THREAD

**Issue by JiriKopriva** [fork52/chess_gif#3]
Hi,
i tried set delay between moves, but i think it has not function. I cant recognize effect for example between delay=2 and delay=100. Thank you for response.

**Comment by fork52** [comment]
Hey!

Try using it this way:
```python3
from chess_gif.gif_maker import Gifmaker

pgn_file_path = 'sample.pgn'	

obj = Gifmaker(pgn_file_path,delay=1)
obj.make_gif('chess_game_delay_1.gif')

obj = Gifmaker(pgn_file_path,delay=5)
obj.make_gif('chess_game_delay_5.gif')
```

**Comment by fork52** [comment]
For reference my attaching the links to the gifs:
[Gif With Delay 1](https://gifyu.com/image/YcK8)
[Gif With Delay 5](https://gifyu.com/image/YcKF)

Hope this helps!

**Comment by JiriKopriva** [comment]
Thank you for quick response, i tried but result is same. 

My script is:

from chess_gif.gif_maker import Gifmaker

pgn_file_path = 'CarlsenGames/1.pgn'
obj = Gifmaker(pgn_file_path, delay=5)
obj.make_gif('CarlsenGames/5sec.gif')

from chess_gif.gif_maker import Gifmaker

pgn_file_path = 'CarlsenGames/1.pgn'
obj = Gifmaker(pgn_file_path, delay=1)
obj.make_gif('CarlsenGames/1sec.gif')

[1sec](https://gifyu.com/image/YcNC)
[5sec](https://gifyu.com/image/YcN0)

Your script is fine, problem is elsewhere.

When i tried change size of board it is okay. 
There is output example:

{'colors': ('#dee3e6', '#8ca2ad'),
 'delay': 5,
 'h_margin': 0,
 'piece_theme': 'merida',
 'side': 70,
 'v_margin': 0}

**Comment by fork52** [comment]
I just updated the code-base of my library by shipping a new version. Try uninstalling the library and installing it again.

```
pip uninstall --no-cache-dir chess-gif
pip install chess-gif==0.0.2
```

I actually hadn't updated it on pypi. That's my fault. 
Thanks for raising the issue. Let me know if it works now!

**Comment by JiriKopriva** [comment]
It is okay! Thank you for fix and your script.
