### ISSUE TITLE
Error: unable to call thumbnail  VipsForeignLoad ... is not a known file format

### ISSUE THREAD

**Issue by MX6464** [fork52/chess_gif#4]
Need some help figuring out what the problem is. My code is: 

from chess_gif.gif_maker import Gifmaker
obj = Gifmaker("/content/Alburt.pgn", h_margin = 20 , v_margin = 80)
obj.make_gif('chess_game.gif')

Getting this error:

Error: unable to call thumbnail
  VipsForeignLoad: "data/piece/merida/bR.svg" is not a known file format

Which comes from :

/usr/local/lib/python3.7/dist-packages/chess_gif/gif_maker.py in make_gif(self, gif_file_path)
    153                         piece_theme = self.kwargs['piece_theme'],
    154                         h_margin=self.kwargs['h_margin'],
--> 155                         v_margin=self.kwargs['v_margin']
    156             )
    157 

/usr/local/lib/python3.7/dist-packages/chess_gif/create_frame.py in __init__(self, colors, side, piece_theme, h_margin, v_margin)
     64         self.piece_theme = piece_theme
     65         # Load the pieces
---> 66         self.pieces = Chess_Pieces(piece_theme, round(side) )
     67 
     68         #Set horizontal and vertical margin

/usr/local/lib/python3.7/dist-packages/chess_gif/create_frame.py in __init__(self, piece_theme, size)
    152         for piece in self.pieces_map:
    153             piece_path = os.path.join(piece_dir,  self.pieces_map[piece]+'.svg')
--> 154             image = VipsImage.thumbnail(piece_path, size , height=size)
    155             image.write_to_file(f"Images/{ self.pieces_map[piece]}.png")
    156 

/usr/local/lib/python3.7/dist-packages/pyvips/vimage.py in call_function(*args, **kwargs)
    133         @_add_doc(name)
    134         def call_function(*args, **kwargs):
--> 135             return pyvips.Operation.call(name, *args, **kwargs)
    136 
    137         return call_function

/usr/local/lib/python3.7/dist-packages/pyvips/voperation.py in call(operation_name, *args, **kwargs)
    291         if vop == ffi.NULL:
    292             vips_lib.vips_object_unref_outputs(op.vobject)
--> 293             raise Error('unable to call {0}'.format(operation_name))
    294         op = Operation(vop)
    295 

I also tried running a unrelated script to test and I'm getting the same pyvips error. 

import pyvips
image = pyvips.Image.new_from_file('/content/PlantDesign17.svg', access='sequential')
image *= [1, 2, 1]
mask = pyvips.Image.new_from_array([[-1, -1, -1],
                                    [-1, 16, -1],
                                    [-1, -1, -1]
                                   ], scale=8)
image = image.conv(mask, precision='integer')
image.write_to_file('x.jpg')

When I try with a .jpg image this code works. Not sure if this is a bug or my error ?

**Comment by fork52** [comment]
Can you tell me what pyvips version you are using? It will help me in reproducing the error.

**Comment by MX6464** [comment]
Name: pyvips
Version: 2.1.15

I tried pyvips 2.1.15 with libvips 8.11.2, 8.11.0, 8.10.6 and got the error. 
I tried pyvips 2.1.15, 2.1.14, 2.1.13 with libvips 8.11.2 and got the error. 


the problem is with my build (configure) of pyvips:
checking for librsvg-2.0 >= 2.40.3 cairo >= 1.2... no
configure: WARNING: librsvg-2.0 >= 2.40.3 or cairo >= 1.2 not found; disabling SVG load via rsvg

File format support
...
SVG load with librsvg-2.0:              no
 (requires librsvg-2.0 2.34.0 or later)




Ahhh this is so complicated with SVG image files. Can you make the code work with png or jpg files for the chess pieces? It seems the only way to get chess-gif to work is if you install Librsvg which is super complicated and requires many dependencies itself. Please let me know if those changes can be made or not :D 



Did you install Librsvg ? 
Are you able to run the example code for pyvips with an svg image?

**Comment by fork52** [comment]
Seems like its a pyvips issue. Closing as its a dependency issue.
